const ALERT="ALERT"
const REFETCH_CHATS="REFETCH_CHATS"

const NEW_ATTATCHMENT="NEW_ATTATCHMENT"
const NEW_MESSAGE_ALERT="NEW_MESSAGE_ALERT"

export {ALERT,REFETCH_CHATS,NEW_ATTATCHMENT,NEW_MESSAGE_ALERT};